version: "3.8"
services:
    web:
        build: 
            context: ./server
        ports: 
            - 8000:8000
    ui:
        build: 
            context: ./front-end
        volumes: 
            - ./front-end:/app/
        ports: 
            - 3000:3000